"""initial schema - all tables

Revision ID: ce2cf05215ee
Revises: 
Create Date: 2025-11-16 19:01:35.136783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2cf05215ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_key', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('change', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('oi', sa.Integer(), nullable=False),
    sa.Column('oi_change', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('oi_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('atp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_vwap_deviation', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('support_level_1', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('support_qty_1', sa.Integer(), nullable=True),
    sa.Column('support_level_2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('support_qty_2', sa.Integer(), nullable=True),
    sa.Column('support_level_3', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('support_qty_3', sa.Integer(), nullable=True),
    sa.Column('support', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resistance_level_1', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resistance_qty_1', sa.Integer(), nullable=True),
    sa.Column('resistance_level_2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resistance_qty_2', sa.Integer(), nullable=True),
    sa.Column('resistance_level_3', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resistance_qty_3', sa.Integer(), nullable=True),
    sa.Column('resistance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tbq', sa.Integer(), nullable=True),
    sa.Column('tsq', sa.Integer(), nullable=True),
    sa.Column('order_book_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('bid_ask_spread', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('big_bid_count', sa.Integer(), nullable=True),
    sa.Column('big_ask_count', sa.Integer(), nullable=True),
    sa.Column('avg_delta', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('avg_gamma', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('avg_theta', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('avg_vega', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('avg_rho', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('avg_iv', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('gamma_spike', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('candle_score', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tick_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_key', 'timestamp', name='uq_candle_instrument_time')
    )
    op.create_index('idx_candles_instrument_time', 'candles', ['instrument_key', 'timestamp'], unique=False)
    op.create_index('idx_candles_score', 'candles', ['instrument_key', 'candle_score'], unique=False)
    op.create_index('idx_candles_timestamp', 'candles', ['timestamp'], unique=False)
    op.create_index(op.f('ix_candles_instrument_key'), 'candles', ['instrument_key'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_key', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('option_type', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('atm_distance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_instruments_active_atm', 'instruments', ['is_active', 'atm_distance'], unique=False)
    op.create_index('idx_instruments_symbol_expiry', 'instruments', ['symbol', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_instruments_expiry_date'), 'instruments', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_instruments_instrument_key'), 'instruments', ['instrument_key'], unique=True)
    op.create_index(op.f('ix_instruments_is_active'), 'instruments', ['is_active'], unique=False)
    op.create_table('seller_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_key', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('panic_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_seller_state_instrument_time', 'seller_states', ['instrument_key', 'timestamp'], unique=False)
    op.create_index('idx_seller_state_recommendation', 'seller_states', ['recommendation'], unique=False)
    op.create_index(op.f('ix_seller_states_instrument_key'), 'seller_states', ['instrument_key'], unique=False)
    op.create_index(op.f('ix_seller_states_timestamp'), 'seller_states', ['timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_key', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('signal_strength', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('panic_detected', sa.Boolean(), nullable=True),
    sa.Column('gamma_spike', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('iv_rise', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('vwap_breach', sa.Boolean(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('suggested_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_instrument_time', 'signals', ['instrument_key', 'timestamp'], unique=False)
    op.create_index('idx_signals_status', 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_instrument_key'), 'signals', ['instrument_key'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_timestamp'), 'signals', ['timestamp'], unique=False)
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=50), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('daily_key_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_key', sa.String(length=50), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('spot_support', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('spot_resistance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference_candle_id', sa.Integer(), nullable=True),
    sa.Column('reference_candle_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_candle_score', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_candle_id'], ['candles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_key', 'trading_date', name='uq_daily_level_instrument_date')
    )
    op.create_index('idx_daily_levels_date', 'daily_key_levels', ['trading_date'], unique=False)
    op.create_index(op.f('ix_daily_key_levels_trading_date'), 'daily_key_levels', ['trading_date'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('instrument_key', sa.String(length=50), nullable=False),
    sa.Column('upstox_order_id', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upstox_order_id')
    )
    op.create_index('idx_orders_instrument', 'orders', ['instrument_key'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_instrument_key'), 'orders', ['instrument_key'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('straddle_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('straddle_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('straddle_vwap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('straddle_deviation', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('ce_candle_id', sa.Integer(), nullable=True),
    sa.Column('pe_candle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ce_candle_id'], ['candles.id'], ),
    sa.ForeignKeyConstraint(['pe_candle_id'], ['candles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'strike_price', name='uq_straddle_time_strike')
    )
    op.create_index('idx_straddle_timestamp', 'straddle_candles', ['timestamp'], unique=False)
    op.create_index(op.f('ix_straddle_candles_timestamp'), 'straddle_candles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_straddle_candles_timestamp'), table_name='straddle_candles')
    op.drop_index('idx_straddle_timestamp', table_name='straddle_candles')
    op.drop_table('straddle_candles')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_instrument_key'), table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_instrument', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_daily_key_levels_trading_date'), table_name='daily_key_levels')
    op.drop_index('idx_daily_levels_date', table_name='daily_key_levels')
    op.drop_table('daily_key_levels')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_signals_timestamp'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_instrument_key'), table_name='signals')
    op.drop_index('idx_signals_status', table_name='signals')
    op.drop_index('idx_signals_instrument_time', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_seller_states_timestamp'), table_name='seller_states')
    op.drop_index(op.f('ix_seller_states_instrument_key'), table_name='seller_states')
    op.drop_index('idx_seller_state_recommendation', table_name='seller_states')
    op.drop_index('idx_seller_state_instrument_time', table_name='seller_states')
    op.drop_table('seller_states')
    op.drop_index(op.f('ix_instruments_is_active'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_instrument_key'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_expiry_date'), table_name='instruments')
    op.drop_index('idx_instruments_symbol_expiry', table_name='instruments')
    op.drop_index('idx_instruments_active_atm', table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_instrument_key'), table_name='candles')
    op.drop_index('idx_candles_timestamp', table_name='candles')
    op.drop_index('idx_candles_score', table_name='candles')
    op.drop_index('idx_candles_instrument_time', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###